name: FRONT_REL_DEPLOY

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - release

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  SSH:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run scripts in server
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.REL_SSH_KEY }}
          host: ${{ secrets.FRONT_REL_HOST }}
          username: ${{ secrets.USER }}
          script: |
            cd SugarFree
            git reset --hard
            git fetch
            git pull
