name: FRONT_REL_DEPLOY

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - release

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  SSH:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run scripts in server
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.REL_SSH_KEY }}
          host: ${{ secrets.FRONT_REL_HOST }}
          username: ${{ secrets.USER }}
          script: |
            cd SugarFree
            git reset --hard
            git fetch
            git pull
      
      - name: action-slack
        uses: 8398a7/action-slack@v3
        with:
         status: ${{ job.status }}
         author_name: Sloth Backend - dev
         fields: repo,commit,message,author # action,eventName,ref,workflow,job,took 추가할 수 있음
         mention: here
         if_mention: failure,cancelled
        env:
         SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: always() # Pick up events even if the job fails or is canceled.
